Repository Linhbui-792002/FE_COFFEE_SHOP_MANAGER, pull requests merged in 2024-06, with the labels that each got.

#24 Feature/23 create component upload image
  next.config.js
  src/components/account/account-form.jsx
  src/components/common/uploadImage/index.js
  src/middleware.js
  src/pages/_app.js
  src/pages/admin/general.js
  src/redux/endPoint/upload.js
  src/redux/store/index.js
Labels: Done

#25 #16 - add employee manager
  .eslintrc.json
  bun.lockb
  package.json
  src/components/account/account-form.jsx
  src/components/common/column-search-props/index.jsx
  src/components/common/layout/admin/sidebar/index.jsx
  src/components/employee/employee-form.jsx
  src/components/employee/index.jsx
  src/constants/index.js
  src/pages/_app.js
  src/pages/admin/employee.js
  src/redux/endPoint/account.js
  src/redux/endPoint/employee.js
  src/utils/index.js
Labels: feature

#30 #16 - add employee manager
  src/components/account/account-form.jsx
  src/components/account/index.jsx
  src/components/common/column-search-props/index.jsx
  src/components/common/uploadImage/index.js
  src/components/employee/employee-form.jsx
  src/components/employee/index.jsx
  src/constants/index.js
  src/middleware.js
  src/pages/admin/employee.js
  src/pages/admin/general.js
  src/redux/endPoint/account.js
  src/redux/endPoint/employee.js
  src/utils/index.js
Labels: Done

#31 Feature/28 create UI menu info manager
  .vscode/settings.json
  src/components/common/uploadImage/index.js
  src/components/employee/employee-form.jsx
  src/components/login/index.jsx
  src/components/menuInfo/index.jsx
  src/components/menuInfo/menuInfo-form.jsx
  src/middleware.js
  src/pages/admin/menu/menu-info.js
  src/redux/api/index.js
  src/redux/endPoint/menuInfo.js
  src/redux/store/index.js
Labels: Done

#32 Feature/#27 create UI product category
  package-lock.json
  src/components/menuInfo/index.jsx
  src/components/productCategory/index.jsx
  src/components/productCategory/produc_category-table.jsx
  src/components/productCategory/product_category_form.jsx
  src/pages/admin/product/product-category.js
  src/redux/api/index.js
  src/redux/endPoint/productCategory.js
  src/redux/store/index.js
Labels: Done

#33 #19 create UI salary manager
  src/components/salary/index.jsx
  src/components/salary/salary-form.jsx
  src/pages/admin/salary.js
  src/redux/api/index.js
  src/redux/endPoint/salary.js
  src/redux/store/index.js
  src/styles/custom-salary-styles.css
  src/styles/globals.css
Labels: Done, feature

#34 Feature/#13 create UI order
  src/components/common/layout/home/default-layout.jsx
  src/components/menuInfo/index.jsx
  src/components/menuInfo/menuInfo-form.jsx
  src/components/order/components/orderList.jsx
  src/components/order/index.jsx
  src/components/order/orderList.jsx
  src/components/order/orderRight.jsx
  src/components/order/productCard.jsx
  src/components/order/productLeft.jsx
  src/components/order/productList.jsx
  src/components/salary/salary-form.jsx
  src/pages/coffee-shop/index.js
  src/redux/slices/orderSlice.js
  src/redux/store/index.js
Labels: feature

#36 #35 add ui change password
  src/components/common/change-password-form/index.jsx
  src/components/common/layout/admin/navbar/index.jsx
  src/redux/api/index.js
  src/redux/endPoint/auth.js
Labels: Done
